# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@hapi/accept-5.0.2" = {
      name = "_at_hapi_slash_accept";
      packageName = "@hapi/accept";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/accept/-/accept-5.0.2.tgz";
        sha512 = "CmzBx/bXUR8451fnZRuZAJRlzgm0Jgu5dltTX/bszmR2lheb9BpyN47Q1RbaGTsvFzn0PXAEs+lXDKfshccYZw==";
      };
    };
    "@hapi/ammo-5.0.1" = {
      name = "_at_hapi_slash_ammo";
      packageName = "@hapi/ammo";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/ammo/-/ammo-5.0.1.tgz";
        sha512 = "FbCNwcTbnQP4VYYhLNGZmA76xb2aHg9AMPiy18NZyWMG310P5KdFGyA9v2rm5ujrIny77dEEIkMOwl0Xv+fSSA==";
      };
    };
    "@hapi/b64-5.0.0" = {
      name = "_at_hapi_slash_b64";
      packageName = "@hapi/b64";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/b64/-/b64-5.0.0.tgz";
        sha512 = "ngu0tSEmrezoiIaNGG6rRvKOUkUuDdf4XTPnONHGYfSGRmDqPZX5oJL6HAdKTo1UQHECbdB4OzhWrfgVppjHUw==";
      };
    };
    "@hapi/boom-9.1.4" = {
      name = "_at_hapi_slash_boom";
      packageName = "@hapi/boom";
      version = "9.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/boom/-/boom-9.1.4.tgz";
        sha512 = "Ls1oH8jaN1vNsqcaHVYJrKmgMcKsC1wcp8bujvXrHaAqD2iDYq3HoOwsxwo09Cuda5R5nC0o0IxlrlTuvPuzSw==";
      };
    };
    "@hapi/bounce-2.0.0" = {
      name = "_at_hapi_slash_bounce";
      packageName = "@hapi/bounce";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/bounce/-/bounce-2.0.0.tgz";
        sha512 = "JesW92uyzOOyuzJKjoLHM1ThiOvHPOLDHw01YV8yh5nCso7sDwJho1h0Ad2N+E62bZyz46TG3xhAi/78Gsct6A==";
      };
    };
    "@hapi/bourne-2.1.0" = {
      name = "_at_hapi_slash_bourne";
      packageName = "@hapi/bourne";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/bourne/-/bourne-2.1.0.tgz";
        sha512 = "i1BpaNDVLJdRBEKeJWkVO6tYX6DMFBuwMhSuWqLsY4ufeTKGVuV5rBsUhxPayXqnnWHgXUAmWK16H/ykO5Wj4Q==";
      };
    };
    "@hapi/call-8.0.1" = {
      name = "_at_hapi_slash_call";
      packageName = "@hapi/call";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/call/-/call-8.0.1.tgz";
        sha512 = "bOff6GTdOnoe5b8oXRV3lwkQSb/LAWylvDMae6RgEWWntd0SHtkYbQukDHKlfaYtVnSAgIavJ0kqszF/AIBb6g==";
      };
    };
    "@hapi/catbox-11.1.1" = {
      name = "_at_hapi_slash_catbox";
      packageName = "@hapi/catbox";
      version = "11.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/catbox/-/catbox-11.1.1.tgz";
        sha512 = "u/8HvB7dD/6X8hsZIpskSDo4yMKpHxFd7NluoylhGrL6cUfYxdQPnvUp9YU2C6F9hsyBVLGulBd9vBN1ebfXOQ==";
      };
    };
    "@hapi/catbox-memory-5.0.1" = {
      name = "_at_hapi_slash_catbox-memory";
      packageName = "@hapi/catbox-memory";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/catbox-memory/-/catbox-memory-5.0.1.tgz";
        sha512 = "QWw9nOYJq5PlvChLWV8i6hQHJYfvdqiXdvTupJFh0eqLZ64Xir7mKNi96d5/ZMUAqXPursfNDIDxjFgoEDUqeQ==";
      };
    };
    "@hapi/content-5.0.2" = {
      name = "_at_hapi_slash_content";
      packageName = "@hapi/content";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/content/-/content-5.0.2.tgz";
        sha512 = "mre4dl1ygd4ZyOH3tiYBrOUBzV7Pu/EOs8VLGf58vtOEECWed8Uuw6B4iR9AN/8uQt42tB04qpVaMyoMQh0oMw==";
      };
    };
    "@hapi/cryptiles-5.1.0" = {
      name = "_at_hapi_slash_cryptiles";
      packageName = "@hapi/cryptiles";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/cryptiles/-/cryptiles-5.1.0.tgz";
        sha512 = "fo9+d1Ba5/FIoMySfMqPBR/7Pa29J2RsiPrl7bkwo5W5o+AN1dAYQRi4SPrPwwVxVGKjgLOEWrsvt1BonJSfLA==";
      };
    };
    "@hapi/file-2.0.0" = {
      name = "_at_hapi_slash_file";
      packageName = "@hapi/file";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/file/-/file-2.0.0.tgz";
        sha512 = "WSrlgpvEqgPWkI18kkGELEZfXr0bYLtr16iIN4Krh9sRnzBZN6nnWxHFxtsnP684wueEySBbXPDg/WfA9xJdBQ==";
      };
    };
    "@hapi/hapi-20.3.0" = {
      name = "_at_hapi_slash_hapi";
      packageName = "@hapi/hapi";
      version = "20.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hapi/-/hapi-20.3.0.tgz";
        sha512 = "zvPSRvaQyF3S6Nev9aiAzko2/hIFZmNSJNcs07qdVaVAvj8dGJSV4fVUuQSnufYJAGiSau+U5LxMLhx79se5WA==";
      };
    };
    "@hapi/heavy-7.0.1" = {
      name = "_at_hapi_slash_heavy";
      packageName = "@hapi/heavy";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/heavy/-/heavy-7.0.1.tgz";
        sha512 = "vJ/vzRQ13MtRzz6Qd4zRHWS3FaUc/5uivV2TIuExGTM9Qk+7Zzqj0e2G7EpE6KztO9SalTbiIkTh7qFKj/33cA==";
      };
    };
    "@hapi/hoek-9.3.0" = {
      name = "_at_hapi_slash_hoek";
      packageName = "@hapi/hoek";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hoek/-/hoek-9.3.0.tgz";
        sha512 = "/c6rf4UJlmHlC9b5BaNvzAcFv7HZ2QHaV0D4/HNlBdvFnvQq8RI4kYdhyPCl7Xj+oWvTWQ8ujhqS53LIgAe6KQ==";
      };
    };
    "@hapi/inert-6.0.5" = {
      name = "_at_hapi_slash_inert";
      packageName = "@hapi/inert";
      version = "6.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/inert/-/inert-6.0.5.tgz";
        sha512 = "eVAdUVhJLmmXLM/Zt7u5H5Vzazs9GKe4zfPK2b97ePHEfs3g/AQkxHfYQjJqMy11hvyB7a21Z6rBEA0R//dtXw==";
      };
    };
    "@hapi/iron-6.0.0" = {
      name = "_at_hapi_slash_iron";
      packageName = "@hapi/iron";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/iron/-/iron-6.0.0.tgz";
        sha512 = "zvGvWDufiTGpTJPG1Y/McN8UqWBu0k/xs/7l++HVU535NLHXsHhy54cfEMdW7EjwKfbBfM9Xy25FmTiobb7Hvw==";
      };
    };
    "@hapi/mimos-6.0.0" = {
      name = "_at_hapi_slash_mimos";
      packageName = "@hapi/mimos";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/mimos/-/mimos-6.0.0.tgz";
        sha512 = "Op/67tr1I+JafN3R3XN5DucVSxKRT/Tc+tUszDwENoNpolxeXkhrJ2Czt6B6AAqrespHoivhgZBWYSuANN9QXg==";
      };
    };
    "@hapi/nigel-4.0.2" = {
      name = "_at_hapi_slash_nigel";
      packageName = "@hapi/nigel";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/nigel/-/nigel-4.0.2.tgz";
        sha512 = "ht2KoEsDW22BxQOEkLEJaqfpoKPXxi7tvabXy7B/77eFtOyG5ZEstfZwxHQcqAiZhp58Ae5vkhEqI03kawkYNw==";
      };
    };
    "@hapi/pez-5.1.0" = {
      name = "_at_hapi_slash_pez";
      packageName = "@hapi/pez";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/pez/-/pez-5.1.0.tgz";
        sha512 = "YfB0btnkLB3lb6Ry/1KifnMPBm5ZPfaAHWFskzOMAgDgXgcBgA+zjpIynyEiBfWEz22DBT8o1e2tAaBdlt8zbw==";
      };
    };
    "@hapi/podium-4.1.3" = {
      name = "_at_hapi_slash_podium";
      packageName = "@hapi/podium";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/podium/-/podium-4.1.3.tgz";
        sha512 = "ljsKGQzLkFqnQxE7qeanvgGj4dejnciErYd30dbrYzUOF/FyS/DOF97qcrT3bhoVwCYmxa6PEMhxfCPlnUcD2g==";
      };
    };
    "@hapi/shot-5.0.5" = {
      name = "_at_hapi_slash_shot";
      packageName = "@hapi/shot";
      version = "5.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/shot/-/shot-5.0.5.tgz";
        sha512 = "x5AMSZ5+j+Paa8KdfCoKh+klB78otxF+vcJR/IoN91Vo2e5ulXIW6HUsFTCU+4W6P/Etaip9nmdAx2zWDimB2A==";
      };
    };
    "@hapi/somever-3.0.1" = {
      name = "_at_hapi_slash_somever";
      packageName = "@hapi/somever";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/somever/-/somever-3.0.1.tgz";
        sha512 = "4ZTSN3YAHtgpY/M4GOtHUXgi6uZtG9nEZfNI6QrArhK0XN/RDVgijlb9kOmXwCR5VclDSkBul9FBvhSuKXx9+w==";
      };
    };
    "@hapi/statehood-7.0.4" = {
      name = "_at_hapi_slash_statehood";
      packageName = "@hapi/statehood";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/statehood/-/statehood-7.0.4.tgz";
        sha512 = "Fia6atroOVmc5+2bNOxF6Zv9vpbNAjEXNcUbWXavDqhnJDlchwUUwKS5LCi5mGtCTxRhUKKHwuxuBZJkmLZ7fw==";
      };
    };
    "@hapi/subtext-7.1.0" = {
      name = "_at_hapi_slash_subtext";
      packageName = "@hapi/subtext";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/subtext/-/subtext-7.1.0.tgz";
        sha512 = "n94cU6hlvsNRIpXaROzBNEJGwxC+HA69q769pChzej84On8vsU14guHDub7Pphr/pqn5b93zV3IkMPDU5AUiXA==";
      };
    };
    "@hapi/teamwork-5.1.1" = {
      name = "_at_hapi_slash_teamwork";
      packageName = "@hapi/teamwork";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/teamwork/-/teamwork-5.1.1.tgz";
        sha512 = "1oPx9AE5TIv+V6Ih54RP9lTZBso3rP8j4Xhb6iSVwPXtAM+sDopl5TFMv5Paw73UnpZJ9gjcrTE1BXrWt9eQrg==";
      };
    };
    "@hapi/topo-5.1.0" = {
      name = "_at_hapi_slash_topo";
      packageName = "@hapi/topo";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/topo/-/topo-5.1.0.tgz";
        sha512 = "foQZKJig7Ob0BMAYBfcJk8d77QtOe7Wo4ox7ff1lQYoNNAb6jwcY1ncdoy2e9wQZzvNy7ODZCYJkK8kzmcAnAg==";
      };
    };
    "@hapi/validate-1.1.3" = {
      name = "_at_hapi_slash_validate";
      packageName = "@hapi/validate";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/validate/-/validate-1.1.3.tgz";
        sha512 = "/XMR0N0wjw0Twzq2pQOzPBZlDzkekGcoCtzO314BpIEsbXdYGthQUbxgkGDf4nhk1+IPDAsXqWjMohRQYO06UA==";
      };
    };
    "@hapi/vise-4.0.0" = {
      name = "_at_hapi_slash_vise";
      packageName = "@hapi/vise";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/vise/-/vise-4.0.0.tgz";
        sha512 = "eYyLkuUiFZTer59h+SGy7hUm+qE9p+UemePTHLlIWppEd+wExn3Df5jO04bFQTm7nleF5V8CtuYQYb+VFpZ6Sg==";
      };
    };
    "@hapi/wreck-17.2.0" = {
      name = "_at_hapi_slash_wreck";
      packageName = "@hapi/wreck";
      version = "17.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/wreck/-/wreck-17.2.0.tgz";
        sha512 = "pJ5kjYoRPYDv+eIuiLQqhGon341fr2bNIYZjuotuPJG/3Ilzr/XtI+JAp0A86E2bYfsS3zBPABuS2ICkaXFT8g==";
      };
    };
    "@socket.io/component-emitter-3.1.0" = {
      name = "_at_socket.io_slash_component-emitter";
      packageName = "@socket.io/component-emitter";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@socket.io/component-emitter/-/component-emitter-3.1.0.tgz";
        sha512 = "+9jVqKhRSpsc591z5vX+X5Yyw+he/HCB4iQ/RYxw35CEPaY1gnsNE43nf9n9AaYjAQrTiI/mOwKUKdUs9vf7Xg==";
      };
    };
    "@types/cookie-0.4.1" = {
      name = "_at_types_slash_cookie";
      packageName = "@types/cookie";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cookie/-/cookie-0.4.1.tgz";
        sha512 = "XW/Aa8APYr6jSVVA1y/DEIZX0/GMKLEVekNG727R8cs56ahETkRAy/3DR7+fJyh7oUgGwNQaRfXCun0+KbWY7Q==";
      };
    };
    "@types/cors-2.8.13" = {
      name = "_at_types_slash_cors";
      packageName = "@types/cors";
      version = "2.8.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cors/-/cors-2.8.13.tgz";
        sha512 = "RG8AStHlUiV5ysZQKq97copd2UmVYw3/pRMLefISZ3S1hK104Cwm7iLQ3fTKx+lsUH2CE8FlLaYeEA2LSeqYUA==";
      };
    };
    "@types/node-20.4.5" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "20.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-20.4.5.tgz";
        sha512 = "rt40Nk13II9JwQBdeYqmbn2Q6IVTA5uPhvSO+JVqdXw/6/4glI6oR9ezty/A9Hg5u7JH4OmYmuQ+XvjKm0Datg==";
      };
    };
    "accepts-1.3.8" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz";
        sha512 = "PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw+NACSaeXEQ+NHcVF7rONl6qcaxV3Uuemwawk+7+SJLw==";
      };
    };
    "base64id-2.0.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-2.0.0.tgz";
        sha512 = "lGe34o6EHj9y3Kts9R4ZYs/Gr+6N7MCaMlIFA3F1R2O5/m7K06AxfSeO5530PEERE6/WyEg3lsuyw4GHlPZHog==";
      };
    };
    "bintrees-1.0.2" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.2.tgz";
        sha512 = "VOMgTMwjAaUG580SXn3LacVgjurrbMme7ZZNYGSSV7mmtY6QQRh0Eg3pwIcntQ77DErK1L0NxkbetjcoXzVwKw==";
      };
    };
    "bufferutil-4.0.7" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.7.tgz";
        sha512 = "kukuqc39WOHtdxtw4UScxF/WVnMFVSQVKhtx3AjZJzhd0RGZZldcrfSEbVsWWe6KNH253574cq5F+wpv0G9pJw==";
      };
    };
    "cookie-0.4.2" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.4.2.tgz";
        sha512 = "aSWTXFzaKWkvHO1Ny/s+ePFpvKsPnjc551iI41v3ny/ow6tBG5Vd+FuqGNhh1LxOmVzOlGUriIlOaokOvhaStA==";
      };
    };
    "cors-2.8.5" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
        sha512 = "KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
      };
    };
    "data-uri-to-buffer-4.0.1" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.1.tgz";
        sha512 = "0R9ikRb668HB7QDxT1vkpuUBtqc53YyAwMwGeUFKRojY/NWKvdZ+9UYtRfGmhqNbRkTSVpMbmyhXipFFv2cb/A==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "dns-over-http-resolver-1.2.3" = {
      name = "dns-over-http-resolver";
      packageName = "dns-over-http-resolver";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-over-http-resolver/-/dns-over-http-resolver-1.2.3.tgz";
        sha512 = "miDiVSI6KSNbi4SVifzO/reD8rMnxgrlnkrlkugOLQpWQTe2qMdHsZp5DmfKjxNE+/T3VAAYLQUZMv9SMr6+AA==";
      };
    };
    "engine.io-6.5.1" = {
      name = "engine.io";
      packageName = "engine.io";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io/-/engine.io-6.5.1.tgz";
        sha512 = "mGqhI+D7YxS9KJMppR6Iuo37Ed3abhU8NdfgSvJSDUafQutrN+sPTncJYTyM9+tkhSmWodKtVYGPPHyXJEwEQA==";
      };
    };
    "engine.io-client-6.5.1" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-6.5.1.tgz";
        sha512 = "hE5wKXH8Ru4L19MbM1GgYV/2Qo54JSMh1rlJbfpa40bEWkCKNo3ol2eOtGmowcr+ysgbI7+SGL+by42Q3pt/Ng==";
      };
    };
    "engine.io-parser-5.1.0" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-5.1.0.tgz";
        sha512 = "enySgNiK5tyZFynt3z7iqBR+Bto9EVVVvDFuTT0ioHCGbzirZVGDGiQjZzEp8hWl6hd5FSVytJGuScX1C1C35w==";
      };
    };
    "err-code-3.0.1" = {
      name = "err-code";
      packageName = "err-code";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-3.0.1.tgz";
        sha512 = "GiaH0KJUewYok+eeY05IIgjtAe4Yltygk9Wqp1V5yVWLdhf0hYZchRjNIT9bb0mSwRcIusT3cx7PJUf3zEIfUA==";
      };
    };
    "fetch-blob-3.2.0" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz";
        sha512 = "7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "ip-regex-4.3.0" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-4.3.0.tgz";
        sha512 = "B9ZWJxHHOHUhUjCPrMpLD4xEq35bUTClHM1S6CBU5ixQnkZmwipwgc96vAd7AAGM9TGHvJR+Uss+/Ak6UphK+Q==";
      };
    };
    "is-ip-3.1.0" = {
      name = "is-ip";
      packageName = "is-ip";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ip/-/is-ip-3.1.0.tgz";
        sha512 = "35vd5necO7IitFPjd/YBeqwWnyDWbuLH9ZXQdMfDA8TEo7pv5X8yfrvVO3xbJbLUlERCMvf6X0hTUamQxCYJ9Q==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "menoetius-0.0.3" = {
      name = "menoetius";
      packageName = "menoetius";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/menoetius/-/menoetius-0.0.3.tgz";
        sha512 = "cm953AR2J/Ya3/lZNJb/gH/927c1tZ1h5uPRytZ4yxZOUwiFmHeulZu3/IT9CImJkLQ50/NEkLW/0bHbExIKEQ==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multiaddr-10.0.1" = {
      name = "multiaddr";
      packageName = "multiaddr";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiaddr/-/multiaddr-10.0.1.tgz";
        sha512 = "G5upNcGzEGuTHkzxezPrrD6CaIHR9uo+7MwqhNVcXTs33IInon4y7nMiGxl2CY5hG7chvYQUQhz5V52/Qe3cbg==";
      };
    };
    "multiformats-9.9.0" = {
      name = "multiformats";
      packageName = "multiformats";
      version = "9.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiformats/-/multiformats-9.9.0.tgz";
        sha512 = "HoMUjhH9T8DDBNT+6xzkrd9ga/XiBI4xLr58LJACwK6G3HTOPeMz4nB4KJs33L2BelrIJa7P0VuNaVF3hMYfjg==";
      };
    };
    "native-fetch-3.0.0" = {
      name = "native-fetch";
      packageName = "native-fetch";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/native-fetch/-/native-fetch-3.0.0.tgz";
        sha512 = "G3Z7vx0IFb/FQ4JxvtqGABsOTIqRWvgQz6e+erkB+JJD6LrszQtMozEHI4EkmgZQvnGHrpLVzUWk7t4sJCIkVw==";
      };
    };
    "negotiator-0.6.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.3.tgz";
        sha512 = "+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.3.2" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.2.tgz";
        sha512 = "dRB78srN/l6gqWulah9SrxeYnxeddIG30+GOqK/9OlLVyLg3HPnr6SqOWTWOXKRwC2eGYCkZ59NNuSgvSrpgOA==";
      };
    };
    "node-gyp-build-4.6.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.6.0.tgz";
        sha512 = "NTZVKn9IylLwUzaKjkas1e4u2DLNcV4rdYagA4PWdPwW87Bi7z+BznyKSRwS/761tV/lzCGXplWsiaMjLqP2zQ==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "prom-client-14.2.0" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "14.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-14.2.0.tgz";
        sha512 = "sF308EhTenb/pDRPakm+WgiN+VdM/T1RaHj1x+MvAuT8UiQP8JmOEbxVqtkbfR4LrvOg5n7ic01kRBDGXjYikA==";
      };
    };
    "receptacle-1.3.2" = {
      name = "receptacle";
      packageName = "receptacle";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/receptacle/-/receptacle-1.3.2.tgz";
        sha512 = "HrsFvqZZheusncQRiEE7GatOAETrARKV/lnfYicIm8lbvp/JQOdADOfhjBd2DajvoszEyxSM6RlAAIZgEoeu/A==";
      };
    };
    "socket.io-4.7.1" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-4.7.1.tgz";
        sha512 = "W+utHys2w//dhFjy7iQQu9sGd3eokCjGbl2r59tyLqNiJJBdIebn3GAKEXBr3osqHTObJi2die/25bCx2zsaaw==";
      };
    };
    "socket.io-adapter-2.5.2" = {
      name = "socket.io-adapter";
      packageName = "socket.io-adapter";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-2.5.2.tgz";
        sha512 = "87C3LO/NOMc+eMcpcxUBebGjkpMDkNBS9tf7KJqcDsmL936EChtVva71Dw2q4tQcuVC+hAUy4an2NO/sYXmwRA==";
      };
    };
    "socket.io-client-4.7.1" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-4.7.1.tgz";
        sha512 = "Qk3Xj8ekbnzKu3faejo4wk2MzXA029XppiXtTF/PkbTg+fcwaTw1PlDrTrrrU4mKoYC4dvlApOnSeyLCKwek2w==";
      };
    };
    "socket.io-parser-4.2.4" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-4.2.4.tgz";
        sha512 = "/GbIKmo8ioc+NIWIhwdecY0ge+qVBSMdgxGygevmdHj24bsfgtCmcUUcQ5ZzcylGFHsN3k4HB4Cgkl96KVnuew==";
      };
    };
    "tdigest-0.1.2" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.2.tgz";
        sha512 = "+G0LLgjjo9BZX2MfdvPfH+MKLCrxlXSYec5DaPYP1fe6Iyhf0/fSmJ0bFiZ1F8BT6cGXl2LpltQptzjXKWEkKA==";
      };
    };
    "uint8arrays-3.1.1" = {
      name = "uint8arrays";
      packageName = "uint8arrays";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint8arrays/-/uint8arrays-3.1.1.tgz";
        sha512 = "+QJa8QRnbdXVpHYjLoTpJIdCTiw9Ir62nocClWuXIq2JIh4Uta0cQsTSpFL678p2CN8B+XSApwcU+pQEqVpKWg==";
      };
    };
    "utf-8-validate-5.0.10" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz";
        sha512 = "Z6czzLq4u8fPOyx7TU6X3dvUZVvoJmxSQ+IcrlmagKhilxlhZgxPK6C5Jqbkw1IDUmFTM+cz9QDnnLTwDz/2gQ==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha512 = "BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
      };
    };
    "web-streams-polyfill-3.2.1" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.2.1.tgz";
        sha512 = "e0MO3wdXWKrLbL0DgGnUV7WHVuw9OUvL4hjgnPkIeEvESk74gAITi5G606JtZPp39cd8HA9VQzCIvA49LpPN5Q==";
      };
    };
    "ws-8.11.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.11.0.tgz";
        sha512 = "HPG3wQd9sNQoT9xHyNCXoDUa+Xw/VevmY9FoHyQ+g+rrMn4j6FB4np7Z0OhdTgjx6MgQLK7jwSy1YecU1+4Asg==";
      };
    };
    "xmlhttprequest-ssl-2.0.0" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-2.0.0.tgz";
        sha512 = "QKxVRxiRACQcVuQEYFsI1hhkrMlrXHPegbbd1yn9UHOmRxY+si12nQYzri3vbzt8VdTTRviqcKxcyllFas5z2A==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  libp2p-webrtc-star-signalling-server = nodeEnv.buildNodePackage {
    name = "libp2p-webrtc-star-signalling-server";
    packageName = "libp2p-webrtc-star-signalling-server";
    version = "0.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/libp2p-webrtc-star-signalling-server/-/libp2p-webrtc-star-signalling-server-0.1.2.tgz";
      sha512 = "AMsvAuX8KFJMGkh3kd6h4iHBPwin0bD8JrDMVK/ezQByHIdK6ddYqwnUHVaL/43HjtOtsdWTnG9wjQ3VAiZwgg==";
    };
    dependencies = [
      sources."@hapi/accept-5.0.2"
      sources."@hapi/ammo-5.0.1"
      sources."@hapi/b64-5.0.0"
      sources."@hapi/boom-9.1.4"
      sources."@hapi/bounce-2.0.0"
      sources."@hapi/bourne-2.1.0"
      sources."@hapi/call-8.0.1"
      sources."@hapi/catbox-11.1.1"
      sources."@hapi/catbox-memory-5.0.1"
      sources."@hapi/content-5.0.2"
      sources."@hapi/cryptiles-5.1.0"
      sources."@hapi/file-2.0.0"
      sources."@hapi/hapi-20.3.0"
      sources."@hapi/heavy-7.0.1"
      sources."@hapi/hoek-9.3.0"
      sources."@hapi/inert-6.0.5"
      sources."@hapi/iron-6.0.0"
      sources."@hapi/mimos-6.0.0"
      sources."@hapi/nigel-4.0.2"
      sources."@hapi/pez-5.1.0"
      sources."@hapi/podium-4.1.3"
      sources."@hapi/shot-5.0.5"
      sources."@hapi/somever-3.0.1"
      sources."@hapi/statehood-7.0.4"
      sources."@hapi/subtext-7.1.0"
      sources."@hapi/teamwork-5.1.1"
      sources."@hapi/topo-5.1.0"
      sources."@hapi/validate-1.1.3"
      sources."@hapi/vise-4.0.0"
      sources."@hapi/wreck-17.2.0"
      sources."@socket.io/component-emitter-3.1.0"
      sources."@types/cookie-0.4.1"
      sources."@types/cors-2.8.13"
      sources."@types/node-20.4.5"
      sources."accepts-1.3.8"
      sources."base64id-2.0.0"
      sources."bintrees-1.0.2"
      sources."bufferutil-4.0.7"
      sources."cookie-0.4.2"
      sources."cors-2.8.5"
      sources."data-uri-to-buffer-4.0.1"
      sources."debug-4.3.4"
      sources."dns-over-http-resolver-1.2.3"
      sources."engine.io-6.5.1"
      sources."engine.io-client-6.5.1"
      sources."engine.io-parser-5.1.0"
      sources."err-code-3.0.1"
      sources."fetch-blob-3.2.0"
      sources."formdata-polyfill-4.0.10"
      sources."ip-regex-4.3.0"
      sources."is-ip-3.1.0"
      sources."lru-cache-6.0.0"
      sources."menoetius-0.0.3"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimist-1.2.8"
      sources."ms-2.1.2"
      sources."multiaddr-10.0.1"
      sources."multiformats-9.9.0"
      sources."native-fetch-3.0.0"
      sources."negotiator-0.6.3"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.3.2"
      sources."node-gyp-build-4.6.0"
      sources."object-assign-4.1.1"
      sources."prom-client-14.2.0"
      sources."receptacle-1.3.2"
      sources."socket.io-4.7.1"
      sources."socket.io-adapter-2.5.2"
      sources."socket.io-client-4.7.1"
      sources."socket.io-parser-4.2.4"
      sources."tdigest-0.1.2"
      sources."uint8arrays-3.1.1"
      sources."utf-8-validate-5.0.10"
      sources."varint-6.0.0"
      sources."vary-1.1.2"
      sources."web-streams-polyfill-3.2.1"
      sources."ws-8.11.0"
      sources."xmlhttprequest-ssl-2.0.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "signalling server to use with the libp2p WebRTC transport";
      homepage = "https://github.com/libp2p/js-libp2p-webrtc-star/tree/master/packages/signalling-server#readme";
      license = "(Apache-2.0 OR MIT)";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
