# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@noble/ed25519-1.7.3" = {
      name = "_at_noble_slash_ed25519";
      packageName = "@noble/ed25519";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/ed25519/-/ed25519-1.7.3.tgz";
        sha512 = "iR8GBkDt0Q3GyaVcIu7mSsVIqnFbkbRzGLWlvhwunacoLwt4J3swfKhfaM6rN6WY+TBGoYT1GtT1mIh2/jGbRQ==";
      };
    };
    "@noble/secp256k1-1.7.1" = {
      name = "_at_noble_slash_secp256k1";
      packageName = "@noble/secp256k1";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@noble/secp256k1/-/secp256k1-1.7.1.tgz";
        sha512 = "hOUk6AyBFmqVrv7k5WAw/LpszxVbj9gGN4JRkIX52fdFAj1UA61KXmZDvqVEm+pOyec3+fIeZB02LYa/pWOArw==";
      };
    };
    "@protobufjs/aspromise-1.1.2" = {
      name = "_at_protobufjs_slash_aspromise";
      packageName = "@protobufjs/aspromise";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/aspromise/-/aspromise-1.1.2.tgz";
        sha512 = "j+gKExEuLmKwvz3OgROXtrJ2UG2x8Ch2YZUxahh+s1F2HZ+wAceUNLkvy6zKCPVRkU++ZWQrdxsUeQXmcg4uoQ==";
      };
    };
    "@protobufjs/base64-1.1.2" = {
      name = "_at_protobufjs_slash_base64";
      packageName = "@protobufjs/base64";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/base64/-/base64-1.1.2.tgz";
        sha512 = "AZkcAA5vnN/v4PDqKyMR5lx7hZttPDgClv83E//FMNhR2TMcLUhfRUBHCmSl0oi9zMgDDqRUJkSxO3wm85+XLg==";
      };
    };
    "@protobufjs/codegen-2.0.4" = {
      name = "_at_protobufjs_slash_codegen";
      packageName = "@protobufjs/codegen";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/codegen/-/codegen-2.0.4.tgz";
        sha512 = "YyFaikqM5sH0ziFZCN3xDC7zeGaB/d0IUb9CATugHWbd1FRFwWwt4ld4OYMPWu5a3Xe01mGAULCdqhMlPl29Jg==";
      };
    };
    "@protobufjs/eventemitter-1.1.0" = {
      name = "_at_protobufjs_slash_eventemitter";
      packageName = "@protobufjs/eventemitter";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/eventemitter/-/eventemitter-1.1.0.tgz";
        sha512 = "j9ednRT81vYJ9OfVuXG6ERSTdEL1xVsNgqpkxMsbIabzSo3goCjDIveeGv5d03om39ML71RdmrGNjG5SReBP/Q==";
      };
    };
    "@protobufjs/fetch-1.1.0" = {
      name = "_at_protobufjs_slash_fetch";
      packageName = "@protobufjs/fetch";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/fetch/-/fetch-1.1.0.tgz";
        sha512 = "lljVXpqXebpsijW71PZaCYeIcE5on1w5DlQy5WH6GLbFryLUrBD4932W/E2BSpfRJWseIL4v/KPgBFxDOIdKpQ==";
      };
    };
    "@protobufjs/float-1.0.2" = {
      name = "_at_protobufjs_slash_float";
      packageName = "@protobufjs/float";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/float/-/float-1.0.2.tgz";
        sha512 = "Ddb+kVXlXst9d+R9PfTIxh1EdNkgoRe5tOX6t01f1lYWOvJnSPDBlG241QLzcyPdoNTsblLUdujGSE4RzrTZGQ==";
      };
    };
    "@protobufjs/inquire-1.1.0" = {
      name = "_at_protobufjs_slash_inquire";
      packageName = "@protobufjs/inquire";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/inquire/-/inquire-1.1.0.tgz";
        sha512 = "kdSefcPdruJiFMVSbn801t4vFK7KB/5gd2fYvrxhuJYg8ILrmn9SKSX2tZdV6V+ksulWqS7aXjBcRXl3wHoD9Q==";
      };
    };
    "@protobufjs/path-1.1.2" = {
      name = "_at_protobufjs_slash_path";
      packageName = "@protobufjs/path";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/path/-/path-1.1.2.tgz";
        sha512 = "6JOcJ5Tm08dOHAbdR3GrvP+yUUfkjG5ePsHYczMFLq3ZmMkAD98cDgcT2iA1lJ9NVwFd4tH/iSSoe44YWkltEA==";
      };
    };
    "@protobufjs/pool-1.1.0" = {
      name = "_at_protobufjs_slash_pool";
      packageName = "@protobufjs/pool";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/pool/-/pool-1.1.0.tgz";
        sha512 = "0kELaGSIDBKvcgS4zkjz1PeddatrjYcmMWOlAuAPwAeccUrPHdUqo/J6LiymHHEiJT5NrF1UVwxY14f+fy4WQw==";
      };
    };
    "@protobufjs/utf8-1.1.0" = {
      name = "_at_protobufjs_slash_utf8";
      packageName = "@protobufjs/utf8";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@protobufjs/utf8/-/utf8-1.1.0.tgz";
        sha512 = "Vvn3zZrhQZkkBE8LSuW3em98c0FwgO4nxzv6OdSxPKJIEKY2bGbHn+mhGIPerzI4twdxaP8/0+06HBpwf345Lw==";
      };
    };
    "@socket.io/component-emitter-3.1.0" = {
      name = "_at_socket.io_slash_component-emitter";
      packageName = "@socket.io/component-emitter";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@socket.io/component-emitter/-/component-emitter-3.1.0.tgz";
        sha512 = "+9jVqKhRSpsc591z5vX+X5Yyw+he/HCB4iQ/RYxw35CEPaY1gnsNE43nf9n9AaYjAQrTiI/mOwKUKdUs9vf7Xg==";
      };
    };
    "@types/long-4.0.2" = {
      name = "_at_types_slash_long";
      packageName = "@types/long";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/long/-/long-4.0.2.tgz";
        sha512 = "MqTGEo5bj5t157U6fA/BiDynNkn0YknVdh48CMPkTSpFTVmvao5UQmm7uEF6xBEo7qIMAlY/JSleYaE6VOdpaA==";
      };
    };
    "@types/minimatch-3.0.5" = {
      name = "_at_types_slash_minimatch";
      packageName = "@types/minimatch";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/minimatch/-/minimatch-3.0.5.tgz";
        sha512 = "Klz949h02Gz2uZCMGwDUSDS1YBlTdDDgbWHi+81l29tQALUtvz4rAYi5uoVhE5Lagoq6DeqAUlbrHvW/mXDgdQ==";
      };
    };
    "@types/node-20.4.5" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "20.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-20.4.5.tgz";
        sha512 = "rt40Nk13II9JwQBdeYqmbn2Q6IVTA5uPhvSO+JVqdXw/6/4glI6oR9ezty/A9Hg5u7JH4OmYmuQ+XvjKm0Datg==";
      };
    };
    "abortable-iterator-3.0.2" = {
      name = "abortable-iterator";
      packageName = "abortable-iterator";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/abortable-iterator/-/abortable-iterator-3.0.2.tgz";
        sha512 = "qVP8HFfTpUQI2F+f1tpTriKDIZ4XrmwCrBCrQeRKO7DKWF3kgoT6NXiNDv2krrGcHxPwmI63eGQiec81sEaWIw==";
      };
    };
    "any-signal-3.0.1" = {
      name = "any-signal";
      packageName = "any-signal";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-signal/-/any-signal-3.0.1.tgz";
        sha512 = "xgZgJtKEa9YmDqXodIgl7Fl1C8yNXr8w6gXjqK3LW4GcEiYT+6AQfJSE/8SPsEpLLmcvbv8YU+qet94UewHxqg==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "browser-readablestream-to-it-1.0.3" = {
      name = "browser-readablestream-to-it";
      packageName = "browser-readablestream-to-it";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-readablestream-to-it/-/browser-readablestream-to-it-1.0.3.tgz";
        sha512 = "+12sHB+Br8HIh6VAMVEG5r3UXCyESIgDW7kzk3BjIXa43DVqVwL7GC5TW3jeh+72dtcH99pPVpw0X8i0jt+/kw==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "bufferutil-4.0.7" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.7.tgz";
        sha512 = "kukuqc39WOHtdxtw4UScxF/WVnMFVSQVKhtx3AjZJzhd0RGZZldcrfSEbVsWWe6KNH253574cq5F+wpv0G9pJw==";
      };
    };
    "class-is-1.1.0" = {
      name = "class-is";
      packageName = "class-is";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-is/-/class-is-1.1.0.tgz";
        sha512 = "rhjH9AG1fvabIDoGRVH587413LPjTZgmDF9fOFCbFJQV4yuocX1mHxxvXI4g3cGwbVY9wAYIoKlg1N79frJKQw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "dns-over-http-resolver-1.2.3" = {
      name = "dns-over-http-resolver";
      packageName = "dns-over-http-resolver";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-over-http-resolver/-/dns-over-http-resolver-1.2.3.tgz";
        sha512 = "miDiVSI6KSNbi4SVifzO/reD8rMnxgrlnkrlkugOLQpWQTe2qMdHsZp5DmfKjxNE+/T3VAAYLQUZMv9SMr6+AA==";
      };
    };
    "electron-fetch-1.9.1" = {
      name = "electron-fetch";
      packageName = "electron-fetch";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-fetch/-/electron-fetch-1.9.1.tgz";
        sha512 = "M9qw6oUILGVrcENMSRRefE1MbHPIz0h79EKIeJWK9v563aT9Qkh8aEHPO1H5vi970wPirNY+jO9OpFoLiMsMGA==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "engine.io-client-6.5.1" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-6.5.1.tgz";
        sha512 = "hE5wKXH8Ru4L19MbM1GgYV/2Qo54JSMh1rlJbfpa40bEWkCKNo3ol2eOtGmowcr+ysgbI7+SGL+by42Q3pt/Ng==";
      };
    };
    "engine.io-parser-5.1.0" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-5.1.0.tgz";
        sha512 = "enySgNiK5tyZFynt3z7iqBR+Bto9EVVVvDFuTT0ioHCGbzirZVGDGiQjZzEp8hWl6hd5FSVytJGuScX1C1C35w==";
      };
    };
    "err-code-2.0.3" = {
      name = "err-code";
      packageName = "err-code";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-2.0.3.tgz";
        sha512 = "2bmlRpNKBxT/CRmPOlyISQpNj+qSeYvcym/uT0Jx2bMOlKLtSy1ZmLuVxSEKKyor/N5yhvp/ZiG1oE3DEYMSFA==";
      };
    };
    "err-code-3.0.1" = {
      name = "err-code";
      packageName = "err-code";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-3.0.1.tgz";
        sha512 = "GiaH0KJUewYok+eeY05IIgjtAe4Yltygk9Wqp1V5yVWLdhf0hYZchRjNIT9bb0mSwRcIusT3cx7PJUf3zEIfUA==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "fast-fifo-1.3.0" = {
      name = "fast-fifo";
      packageName = "fast-fifo";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-fifo/-/fast-fifo-1.3.0.tgz";
        sha512 = "IgfweLvEpwyA4WgiQe9Nx6VV2QkML2NkvZnk1oKnIzXgXdWxuhF7zw4DvLTPZJn6PIUneiAXPF24QmoEqHTjyw==";
      };
    };
    "get-browser-rtc-1.1.0" = {
      name = "get-browser-rtc";
      packageName = "get-browser-rtc";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-browser-rtc/-/get-browser-rtc-1.1.0.tgz";
        sha512 = "MghbMJ61EJrRsDe7w1Bvqt3ZsBuqhce5nrn/XAwgwOXhcsz53/ltdxOse1h/8eKXj5slzxdsz56g5rzOFSGwfQ==";
      };
    };
    "get-iterator-1.0.2" = {
      name = "get-iterator";
      packageName = "get-iterator";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-iterator/-/get-iterator-1.0.2.tgz";
        sha512 = "v+dm9bNVfOYsY1OrhaCrmyOcYoSeVvbt+hHZ0Au+T+p1y+0Uyj9aMaGIeUTT6xdpRbWzDeYKvfOslPhggQMcsg==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ip-address-8.1.0" = {
      name = "ip-address";
      packageName = "ip-address";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-address/-/ip-address-8.1.0.tgz";
        sha512 = "Wz91gZKpNKoXtqvY8ScarKYwhXoK4r/b5QuT+uywe/azv0/nUCo7Bh0IRRI7F9DHR06kJNWtzMGLIbXavngbKA==";
      };
    };
    "ip-regex-4.3.0" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-4.3.0.tgz";
        sha512 = "B9ZWJxHHOHUhUjCPrMpLD4xEq35bUTClHM1S6CBU5ixQnkZmwipwgc96vAd7AAGM9TGHvJR+Uss+/Ak6UphK+Q==";
      };
    };
    "ipaddr.js-2.1.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-2.1.0.tgz";
        sha512 = "LlbxQ7xKzfBusov6UMi4MFpEg0m+mAm9xyNGEduwXMEDuf4WfzB/RZwMVYEd7IKGvh4IUkEXYxtAVu9T3OelJQ==";
      };
    };
    "ipfs-utils-9.0.14" = {
      name = "ipfs-utils";
      packageName = "ipfs-utils";
      version = "9.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipfs-utils/-/ipfs-utils-9.0.14.tgz";
        sha512 = "zIaiEGX18QATxgaS0/EOQNoo33W0islREABAcxXE8n7y2MGAlB+hdsxXn4J0hGZge8IqVQhW8sWIb+oJz2yEvg==";
      };
    };
    "is-electron-2.2.2" = {
      name = "is-electron";
      packageName = "is-electron";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-electron/-/is-electron-2.2.2.tgz";
        sha512 = "FO/Rhvz5tuw4MCWkpMzHFKWD2LsfHzIb7i6MdPYZ/KW7AlxawyLkqdy+jPZP1WubqEADE3O4FUENlJHDfQASRg==";
      };
    };
    "is-ip-3.1.0" = {
      name = "is-ip";
      packageName = "is-ip";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ip/-/is-ip-3.1.0.tgz";
        sha512 = "35vd5necO7IitFPjd/YBeqwWnyDWbuLH9ZXQdMfDA8TEo7pv5X8yfrvVO3xbJbLUlERCMvf6X0hTUamQxCYJ9Q==";
      };
    };
    "is-loopback-addr-1.0.1" = {
      name = "is-loopback-addr";
      packageName = "is-loopback-addr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-loopback-addr/-/is-loopback-addr-1.0.1.tgz";
        sha512 = "DhWU/kqY7X2F6KrrVTu7mHlbd2Pbo4D1YkAzasBMjQs6lJAoefxaA6m6CpSX0K6pjt9D0b9PNFI5zduy/vzOYw==";
      };
    };
    "is-plain-obj-2.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-2.1.0.tgz";
        sha512 = "YWnfyRwxL/+SsrWYfOpUtz5b3YD+nyfkHvjbcanzk8zgyO4ASD67uVMRt8k5bM4lLMDnXfriRhOpemw+NfT1eA==";
      };
    };
    "iso-random-stream-2.0.2" = {
      name = "iso-random-stream";
      packageName = "iso-random-stream";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/iso-random-stream/-/iso-random-stream-2.0.2.tgz";
        sha512 = "yJvs+Nnelic1L2vH2JzWvvPQFA4r7kSTnpST/+LkAQjSz0hos2oqLD+qIVi9Qk38Hoe7mNDt3j0S27R58MVjLQ==";
      };
    };
    "iso-url-1.2.1" = {
      name = "iso-url";
      packageName = "iso-url";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/iso-url/-/iso-url-1.2.1.tgz";
        sha512 = "9JPDgCN4B7QPkLtYAAOrEuAWvP9rWvR5offAr0/SeF046wIkglqH3VXgYYP6NcsKslH80UIVgmPqNe3j7tG2ng==";
      };
    };
    "it-all-1.0.6" = {
      name = "it-all";
      packageName = "it-all";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/it-all/-/it-all-1.0.6.tgz";
        sha512 = "3cmCc6Heqe3uWi3CVM/k51fa/XbMFpQVzFoDsV0IZNHSQDyAXl3c4MjHkFX5kF3922OGj7Myv1nSEUgRtcuM1A==";
      };
    };
    "it-glob-1.0.2" = {
      name = "it-glob";
      packageName = "it-glob";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/it-glob/-/it-glob-1.0.2.tgz";
        sha512 = "Ch2Dzhw4URfB9L/0ZHyY+uqOnKvBNeS/SMcRiPmJfpHiM0TsUZn+GkpcZxAoF3dJVdPm/PuIk3A4wlV7SUo23Q==";
      };
    };
    "it-pipe-1.1.0" = {
      name = "it-pipe";
      packageName = "it-pipe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/it-pipe/-/it-pipe-1.1.0.tgz";
        sha512 = "lF0/3qTVeth13TOnHVs0BTFaziwQF7m5Gg+E6JV0BXcLKutC92YjSi7bASgkPOXaLEb+YvNZrPorGMBIJvZfxg==";
      };
    };
    "it-to-stream-1.0.0" = {
      name = "it-to-stream";
      packageName = "it-to-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/it-to-stream/-/it-to-stream-1.0.0.tgz";
        sha512 = "pLULMZMAB/+vbdvbZtebC0nWBTbG581lk6w8P7DfIIIKUfa8FbY7Oi0FxZcFPbxvISs7A9E+cMpLDBc1XhpAOA==";
      };
    };
    "jsbn-1.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-1.1.0.tgz";
        sha512 = "4bYVV3aAMtDTTu4+xsDYa6sy9GyJ69/amsu9sYF2zqjiEoZA5xJi3BrfX3uY+/IekIu7MwdObdbDWpoZdBv3/A==";
      };
    };
    "libp2p-crypto-0.21.2" = {
      name = "libp2p-crypto";
      packageName = "libp2p-crypto";
      version = "0.21.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/libp2p-crypto/-/libp2p-crypto-0.21.2.tgz";
        sha512 = "EXFrhSpiHtJ+/L8xXDvQNK5VjUMG51u878jzZcaT5XhuN/zFg6PWJFnl/qB2Y2j7eMWnvCRP7Kp+ua2H36cG4g==";
      };
    };
    "libp2p-utils-0.4.1" = {
      name = "libp2p-utils";
      packageName = "libp2p-utils";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/libp2p-utils/-/libp2p-utils-0.4.1.tgz";
        sha512 = "kq/US2unamiyY+YwP47dO1uqpAdcbdYI2Fzi9JIEhjfPBaD1MR/uyQ/YP7ABthl3EaxAjIQYd1TVp85d6QKAtQ==";
      };
    };
    "libp2p-webrtc-peer-10.0.1" = {
      name = "libp2p-webrtc-peer";
      packageName = "libp2p-webrtc-peer";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/libp2p-webrtc-peer/-/libp2p-webrtc-peer-10.0.1.tgz";
        sha512 = "Qi/YVrSI5sjU+iBvr1iAjGrakIEvzCS8S76v4q43jjlDb6Wj+S4OnFLH/uRlt7eLXcx4vlaI6huMzYrUAoopMg==";
      };
    };
    "long-4.0.0" = {
      name = "long";
      packageName = "long";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/long/-/long-4.0.0.tgz";
        sha512 = "XsP+KhQif4bjX1kbuSiySJFNAehNxgLb6hPRGJ9QsUr8ajHkuXGdrHmFUTUUXhDwVX2R5bY4JNZEwbUiMhV+MA==";
      };
    };
    "mafmt-10.0.0" = {
      name = "mafmt";
      packageName = "mafmt";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mafmt/-/mafmt-10.0.0.tgz";
        sha512 = "K1bziJOXcnepfztu+2Xy9FLKVLaFMDuspmiyJIYRxnO0WOxFSV7XKSdMxMrVZxcvg1+YjlTIvSGTImUHU2k4Aw==";
      };
    };
    "merge-options-3.0.4" = {
      name = "merge-options";
      packageName = "merge-options";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-options/-/merge-options-3.0.4.tgz";
        sha512 = "2Sug1+knBjkaMsMgf1ctR1Ujx+Ayku4EdJN4Z+C2+JzoeF7A3OZ9KM2GY0CpQS51NR61LTurMJrRKPhSs3ZRTQ==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multiaddr-10.0.1" = {
      name = "multiaddr";
      packageName = "multiaddr";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiaddr/-/multiaddr-10.0.1.tgz";
        sha512 = "G5upNcGzEGuTHkzxezPrrD6CaIHR9uo+7MwqhNVcXTs33IInon4y7nMiGxl2CY5hG7chvYQUQhz5V52/Qe3cbg==";
      };
    };
    "multiformats-9.9.0" = {
      name = "multiformats";
      packageName = "multiformats";
      version = "9.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiformats/-/multiformats-9.9.0.tgz";
        sha512 = "HoMUjhH9T8DDBNT+6xzkrd9ga/XiBI4xLr58LJACwK6G3HTOPeMz4nB4KJs33L2BelrIJa7P0VuNaVF3hMYfjg==";
      };
    };
    "nanoid-3.3.6" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.6.tgz";
        sha512 = "BGcqMMJuToF7i1rt+2PWSNVnWIkGCU78jBG3RxO/bZlnZPK2Cmi2QaffxGO/2RvWi9sL+FAiRiXMgsyxQ1DIDA==";
      };
    };
    "native-fetch-3.0.0" = {
      name = "native-fetch";
      packageName = "native-fetch";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/native-fetch/-/native-fetch-3.0.0.tgz";
        sha512 = "G3Z7vx0IFb/FQ4JxvtqGABsOTIqRWvgQz6e+erkB+JJD6LrszQtMozEHI4EkmgZQvnGHrpLVzUWk7t4sJCIkVw==";
      };
    };
    "netmask-2.0.2" = {
      name = "netmask";
      packageName = "netmask";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-2.0.2.tgz";
        sha512 = "dBpDMdxv9Irdq66304OLfEmQ9tbNRFnFTuZiLo+bD+r332bBmMJ8GBLXklIXXgxd3+v9+KUnZaUR5PJMa75Gsg==";
      };
    };
    "node-fetch-2.6.12" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.12.tgz";
        sha512 = "C/fGU2E8ToujUivIO0H+tpQ6HWo4eEmchoPIoXtxCrVghxdKq+QOHqEZW7tuP3KlV3bC8FRMO5nMCC7Zm1VP6g==";
      };
    };
    "node-forge-1.3.1" = {
      name = "node-forge";
      packageName = "node-forge";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-forge/-/node-forge-1.3.1.tgz";
        sha512 = "dPEtOeMvF9VMcYV/1Wb8CPoVAXtp6MKMlcbAt4ddqmGqUJ6fQZFXkNZNkNlfevtNkGtaSoXf/vNNNSvgrdXwtA==";
      };
    };
    "node-gyp-build-4.6.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.6.0.tgz";
        sha512 = "NTZVKn9IylLwUzaKjkas1e4u2DLNcV4rdYagA4PWdPwW87Bi7z+BznyKSRwS/761tV/lzCGXplWsiaMjLqP2zQ==";
      };
    };
    "p-defer-3.0.0" = {
      name = "p-defer";
      packageName = "p-defer";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-defer/-/p-defer-3.0.0.tgz";
        sha512 = "ugZxsxmtTln604yeYd29EGrNhazN2lywetzpKhfmQjW/VJmhpDmWbiX+h0zL8V91R0UXkhb3KtPmyq9PZw3aYw==";
      };
    };
    "p-fifo-1.0.0" = {
      name = "p-fifo";
      packageName = "p-fifo";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-fifo/-/p-fifo-1.0.0.tgz";
        sha512 = "IjoCxXW48tqdtDFz6fqo5q1UfFVjjVZe8TC1QRflvNUJtNfCUhxOUw6MOVZhDPjqhSzc26xKdugsO17gmzd5+A==";
      };
    };
    "peer-id-0.16.0" = {
      name = "peer-id";
      packageName = "peer-id";
      version = "0.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/peer-id/-/peer-id-0.16.0.tgz";
        sha512 = "EmL7FurFUduU9m1PS9cfJ5TAuCvxKQ7DKpfx3Yj6IKWyBRtosriFuOag/l3ni/dtPgPLwiA4R9IvpL7hsDLJuQ==";
      };
    };
    "private-ip-2.3.4" = {
      name = "private-ip";
      packageName = "private-ip";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/private-ip/-/private-ip-2.3.4.tgz";
        sha512 = "ts/YFVwfBeLq61f9+KsOhXW6RH0wvY0gU50R6QZYzgFhggyyLK6WDFeYdjfi/HMnBm2hecLvsR3PB3JcRxDk+A==";
      };
    };
    "protobufjs-6.11.3" = {
      name = "protobufjs";
      packageName = "protobufjs";
      version = "6.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/protobufjs/-/protobufjs-6.11.3.tgz";
        sha512 = "xL96WDdCZYdU7Slin569tFX712BxsxslWwAfAhCYjQKGTq7dAU91Lomy6nLLhh/dyGhk/YH4TwTSRxTzhuHyZg==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "react-native-fetch-api-3.0.0" = {
      name = "react-native-fetch-api";
      packageName = "react-native-fetch-api";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-native-fetch-api/-/react-native-fetch-api-3.0.0.tgz";
        sha512 = "g2rtqPjdroaboDKTsJCTlcmtw54E25OjyaunUP0anOZn4Fuo2IKs8BVfe02zVggA/UysbmfSnRJIqtNkAgggNA==";
      };
    };
    "readable-stream-3.6.2" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.2.tgz";
        sha512 = "9u/sniCrY3D5WdsERHzHE4G2YCXqoG5FTHUiCC4SIbr6XcLZBY05ya9EKjYek9O5xOAwjGq+1JdGBAS7Q9ScoA==";
      };
    };
    "receptacle-1.3.2" = {
      name = "receptacle";
      packageName = "receptacle";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/receptacle/-/receptacle-1.3.2.tgz";
        sha512 = "HrsFvqZZheusncQRiEE7GatOAETrARKV/lnfYicIm8lbvp/JQOdADOfhjBd2DajvoszEyxSM6RlAAIZgEoeu/A==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "socket.io-client-4.7.1" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "4.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-4.7.1.tgz";
        sha512 = "Qk3Xj8ekbnzKu3faejo4wk2MzXA029XppiXtTF/PkbTg+fcwaTw1PlDrTrrrU4mKoYC4dvlApOnSeyLCKwek2w==";
      };
    };
    "socket.io-parser-4.2.4" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-4.2.4.tgz";
        sha512 = "/GbIKmo8ioc+NIWIhwdecY0ge+qVBSMdgxGygevmdHj24bsfgtCmcUUcQ5ZzcylGFHsN3k4HB4Cgkl96KVnuew==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "stream-to-it-0.2.4" = {
      name = "stream-to-it";
      packageName = "stream-to-it";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-it/-/stream-to-it-0.2.4.tgz";
        sha512 = "4vEbkSs83OahpmBybNJXlJd7d6/RxzkkSdT3I0mnGt79Xd2Kk+e1JqbvAvsQfCeKj3aKb0QIWkyK3/n0j506vQ==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "uint8arrays-3.1.1" = {
      name = "uint8arrays";
      packageName = "uint8arrays";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint8arrays/-/uint8arrays-3.1.1.tgz";
        sha512 = "+QJa8QRnbdXVpHYjLoTpJIdCTiw9Ir62nocClWuXIq2JIh4Uta0cQsTSpFL678p2CN8B+XSApwcU+pQEqVpKWg==";
      };
    };
    "utf-8-validate-5.0.10" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "5.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz";
        sha512 = "Z6czzLq4u8fPOyx7TU6X3dvUZVvoJmxSQ+IcrlmagKhilxlhZgxPK6C5Jqbkw1IDUmFTM+cz9QDnnLTwDz/2gQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "ws-8.11.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.11.0.tgz";
        sha512 = "HPG3wQd9sNQoT9xHyNCXoDUa+Xw/VevmY9FoHyQ+g+rrMn4j6FB4np7Z0OhdTgjx6MgQLK7jwSy1YecU1+4Asg==";
      };
    };
    "xmlhttprequest-ssl-2.0.0" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-2.0.0.tgz";
        sha512 = "QKxVRxiRACQcVuQEYFsI1hhkrMlrXHPegbbd1yn9UHOmRxY+si12nQYzri3vbzt8VdTTRviqcKxcyllFas5z2A==";
      };
    };
  };
in
{
  libp2p-webrtc-star = nodeEnv.buildNodePackage {
    name = "libp2p-webrtc-star";
    packageName = "libp2p-webrtc-star";
    version = "0.25.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/libp2p-webrtc-star/-/libp2p-webrtc-star-0.25.0.tgz";
      sha512 = "SyXjHDrm+qlKQE5HIddrUCSwkxCIJ30PAH4ZVNNADkC0F5IVQY9EoVJ+/rrzZuDDqccnS15TgxW13vmybX96bQ==";
    };
    dependencies = [
      sources."@noble/ed25519-1.7.3"
      sources."@noble/secp256k1-1.7.1"
      sources."@protobufjs/aspromise-1.1.2"
      sources."@protobufjs/base64-1.1.2"
      sources."@protobufjs/codegen-2.0.4"
      sources."@protobufjs/eventemitter-1.1.0"
      sources."@protobufjs/fetch-1.1.0"
      sources."@protobufjs/float-1.0.2"
      sources."@protobufjs/inquire-1.1.0"
      sources."@protobufjs/path-1.1.2"
      sources."@protobufjs/pool-1.1.0"
      sources."@protobufjs/utf8-1.1.0"
      sources."@socket.io/component-emitter-3.1.0"
      sources."@types/long-4.0.2"
      sources."@types/minimatch-3.0.5"
      sources."@types/node-20.4.5"
      sources."abortable-iterator-3.0.2"
      sources."any-signal-3.0.1"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."brace-expansion-1.1.11"
      sources."browser-readablestream-to-it-1.0.3"
      sources."buffer-6.0.3"
      sources."bufferutil-4.0.7"
      sources."class-is-1.1.0"
      sources."concat-map-0.0.1"
      sources."debug-4.3.4"
      sources."dns-over-http-resolver-1.2.3"
      sources."electron-fetch-1.9.1"
      sources."encoding-0.1.13"
      sources."engine.io-client-6.5.1"
      sources."engine.io-parser-5.1.0"
      sources."err-code-3.0.1"
      sources."events-3.3.0"
      sources."fast-fifo-1.3.0"
      sources."get-browser-rtc-1.1.0"
      sources."get-iterator-1.0.2"
      sources."iconv-lite-0.6.3"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."ip-address-8.1.0"
      sources."ip-regex-4.3.0"
      sources."ipaddr.js-2.1.0"
      sources."ipfs-utils-9.0.14"
      sources."is-electron-2.2.2"
      sources."is-ip-3.1.0"
      sources."is-loopback-addr-1.0.1"
      sources."is-plain-obj-2.1.0"
      sources."iso-random-stream-2.0.2"
      sources."iso-url-1.2.1"
      sources."it-all-1.0.6"
      sources."it-glob-1.0.2"
      sources."it-pipe-1.1.0"
      sources."it-to-stream-1.0.0"
      sources."jsbn-1.1.0"
      sources."libp2p-crypto-0.21.2"
      sources."libp2p-utils-0.4.1"
      (sources."libp2p-webrtc-peer-10.0.1" // {
        dependencies = [
          sources."err-code-2.0.3"
        ];
      })
      sources."long-4.0.0"
      sources."mafmt-10.0.0"
      sources."merge-options-3.0.4"
      sources."minimatch-3.1.2"
      sources."ms-2.1.2"
      sources."multiaddr-10.0.1"
      sources."multiformats-9.9.0"
      sources."nanoid-3.3.6"
      sources."native-fetch-3.0.0"
      sources."netmask-2.0.2"
      sources."node-fetch-2.6.12"
      sources."node-forge-1.3.1"
      sources."node-gyp-build-4.6.0"
      sources."p-defer-3.0.0"
      sources."p-fifo-1.0.0"
      sources."peer-id-0.16.0"
      sources."private-ip-2.3.4"
      sources."protobufjs-6.11.3"
      sources."queue-microtask-1.2.3"
      sources."randombytes-2.1.0"
      sources."react-native-fetch-api-3.0.0"
      sources."readable-stream-3.6.2"
      sources."receptacle-1.3.2"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."socket.io-client-4.7.1"
      sources."socket.io-parser-4.2.4"
      sources."sprintf-js-1.1.2"
      sources."stream-to-it-0.2.4"
      sources."string_decoder-1.3.0"
      sources."tr46-0.0.3"
      sources."uint8arrays-3.1.1"
      sources."utf-8-validate-5.0.10"
      sources."util-deprecate-1.0.2"
      sources."varint-6.0.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."ws-8.11.0"
      sources."xmlhttprequest-ssl-2.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "libp2p WebRTC transport that includes a discovery mechanism provided by the signalling-star";
      homepage = "https://github.com/libp2p/js-libp2p-webrtc-star/tree/master/packages/transport#readme";
      license = "(Apache-2.0 OR MIT)";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
